
export default function MessageList() {

   //TODO - LISTA DE MENSAGENS DENTRO DO CHAT, PODE SER UM COMPONENTE QUE VAI RENDERIZAR TODAS AS MENSAGENS COMO UMA LISTA, OU CADA MENSAGEM VAI SER UM COMPONENTE, DECIDA
  return (
    <div>

    </div>
  )
}
