
function App() {

  //TODO - AINDA NAO SEI OQUE VAI TER AQUI, TALVEZ O CHATROOMLIST E O NAVBAR? JA QUE O RESTO FICA UM DENTRO DO OUTRO E O LOGIN E REGISTER SÃO INDIVIDUAIS PARA AUTENTICAÇÃO E LIBERAÇÃO DA ENTRADA NO APP

  // * ESTAMOS USANDO MATERIAL UI
  return (
    <>

    </>
  )
}

export default App
